/**
 * Helper functions to extract session and authentication information
 * Used by API endpoints to determine user privileges and apply proper filters
 */

import { NextRequest } from 'next/server';
import { auth } from '@/auth';
import { query as dbQuery } from '@/app/lib/db';
import jwt from 'jsonwebtoken';

const DEFAULT_UUID = '00000000-0000-0000-0000-000000000000';
const { APP_SECRET } = process.env;

export interface SessionInfo {
  uuid: string;
  rights: number;
  collaborators: string[];
  isPublic: boolean;
  isUNDP: boolean;
  email?: string;
}

/**
 * Extract session information from Next-Auth session or JWT access token
 * Supports both authenticated sessions and API token access
 */
export async function getSessionInfo(request?: NextRequest): Promise<SessionInfo> {
  // Try to get session from NextAuth v5
  const session = await auth();
  
  if (session?.user) {
    const uuid = session.user.uuid || DEFAULT_UUID;
    const rights = session.user.rights ?? 0;
    const email = session.user.email || '';
    const isUNDP = email.endsWith('@undp.org');
    
    // Get team collaborators for this user
    const collaborators = await getCollaborators(uuid);
    
    return {
      uuid,
      rights,
      collaborators: [uuid, ...collaborators], // Include user in collaborators list
      isPublic: false,
      isUNDP,
      email
    };
  }
  
  // If no session, check for JWT access token in headers
  if (request) {
    // Check if middleware already validated token and added headers
    const apiUserUuid = request.headers.get('x-api-user-uuid');
    const apiUserEmail = request.headers.get('x-api-user-email');
    const apiUserRights = request.headers.get('x-api-user-rights');
    const apiAuthenticated = request.headers.get('x-api-authenticated');
    
    if (apiAuthenticated === 'true' && apiUserUuid) {
      const uuid = apiUserUuid;
      const rights = parseInt(apiUserRights || '1', 10);
      const email = apiUserEmail || '';
      const isUNDP = email.endsWith('@undp.org');
      
      // Get team collaborators
      const collaborators = await getCollaborators(uuid);
      
      return {
        uuid,
        rights,
        collaborators: [uuid, ...collaborators],
        isPublic: false,
        isUNDP,
        email
      };
    }
    
    // If middleware didn't validate, try to validate token directly
    const authHeader = request.headers.get('authorization');
    const accessToken = authHeader?.replace('Bearer ', '') || request.headers.get('x-access-token');
    
    if (accessToken) {
      const tokenInfo = await validateJWT(accessToken);
      if (tokenInfo) {
        return tokenInfo;
      }
    }
  }
  
  // No authentication found - return public/guest user
  return {
    uuid: DEFAULT_UUID,
    rights: 0,
    collaborators: [],
    isPublic: true,
    isUNDP: false
  };
}

/**
 * Get team member UUIDs for a given user
 * Returns array of collaborator UUIDs (excluding the user themselves)
 */
async function getCollaborators(uuid: string): Promise<string[]> {
  try {
    const result = await dbQuery('general', `
      SELECT DISTINCT tm2.member::text as collaborator
      FROM team_members tm1
      INNER JOIN team_members tm2 ON tm1.team = tm2.team
      WHERE tm1.member = $1 AND tm2.member != $1
    `, [uuid]);
    
    return result.rows.map((row: any) => row.collaborator);
  } catch (error) {
    console.error('Error fetching collaborators:', error);
    return [];
  }
}

/**
 * Validate JWT access token and extract user information
 * JWT tokens are generated by /api/auth/api-token endpoint
 */
async function validateJWT(token: string): Promise<SessionInfo | null> {
  try {
    // Verify and decode JWT token
    const decoded = jwt.verify(token, APP_SECRET || 'fallback-secret-key') as any;
    
    // Validate token type (must be api_access)
    if (decoded.type !== 'api_access') {
      console.error('Invalid JWT token type:', decoded.type);
      return null;
    }
    
    const uuid = decoded.uuid;
    const rights = decoded.rights ?? 1;
    const email = decoded.email || '';
    const isUNDP = email.endsWith('@undp.org');
    
    // Get team collaborators
    const collaborators = await getCollaborators(uuid);
    
    return {
      uuid,
      rights,
      collaborators: [uuid, ...collaborators],
      isPublic: false,
      isUNDP,
      email
    };
  } catch (error) {
    // Token is invalid, expired, or malformed
    console.error('JWT validation error:', error);
    return null;
  }
}

/**
 * Helper to determine if user can see private/team pads
 */
export function canAccessPrivatePads(sessionInfo: SessionInfo): boolean {
  return !sessionInfo.isPublic && sessionInfo.uuid !== DEFAULT_UUID;
}

/**
 * Helper to determine if user has admin rights
 */
export function isAdmin(sessionInfo: SessionInfo): boolean {
  return sessionInfo.rights >= 3;
}

/**
 * Helper to determine if user is reviewing pads
 */
export async function getReviewingPads(uuid: string): Promise<number[]> {
  if (uuid === DEFAULT_UUID) return [];
  
  try {
    const result = await dbQuery('general', `
      SELECT review FROM reviews WHERE reviewer = $1
    `, [uuid]);
    
    return result.rows.map((row: any) => row.review);
  } catch (error) {
    console.error('Error fetching reviewing pads:', error);
    return [];
  }
}
