import { NextRequest, NextResponse } from 'next/server';
import getSession from '@/app/lib/session';
import { query } from '@/app/lib/db';
import { sendEmail } from '@/app/lib/helpers';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';

export async function GET(request: NextRequest) {
  return handleShareRequest(request);
}

export async function POST(request: NextRequest) {
  return handleShareRequest(request);
}

async function handleShareRequest(request: NextRequest) {
  try {
    const session = await getSession();
    const { uuid, rights, name: username, email: c_email } = session || {};

    // Get parameters from query string or body
    const searchParams = request.nextUrl.searchParams;
    let params: { pinboard?: string; email?: string } = {};

    if (request.method === 'GET') {
      params = {
        pinboard: searchParams.get('pinboard') || undefined,
        email: searchParams.get('email') || undefined,
      };
    } else {
      const body = await request.json().catch(() => ({}));
      params = body;
    }

    const { pinboard, email } = params;

    // Validation
    if (!uuid || !rights) {
      return NextResponse.json(
        { message: 'Unauthorized', success: false },
        { status: 401 }
      );
    }

    if (!pinboard) {
      return NextResponse.json(
        { message: 'Please provide a board ID', success: false },
        { status: 400 }
      );
    }

    if (!email) {
      return NextResponse.json(
        { message: 'Please provide an email.', success: false },
        { status: 400 }
      );
    }

    // Transaction to handle user creation/retrieval and contributor addition
    const result = await query('general', 'SELECT 1').then(async () => {
      // Check if user exists
      const existingUser = await query(
        'general',
        'SELECT * FROM users WHERE email = $1',
        [email]
      );

      let user = existingUser.rows[0];

      // If user doesn't exist, create them
      if (!user) {
        const generatePassword = () => crypto.randomBytes(8).toString('hex');
        const autoGeneratedPassword = generatePassword();
        const hashedPassword = bcrypt.hashSync(autoGeneratedPassword, 10);
        const name = email.split('@')[0];

        const newUser = await query(
          'general',
          `INSERT INTO users (iso3, name, position, email, password, rights, confirmed, created_at) 
           VALUES ($1, $2, $3, $4, $5, $6, $7, NOW()) 
           RETURNING *`,
          ['NUL', name, 'Contributor', email, hashedPassword, 1, false]
        );

        user = newUser.rows[0];
      }

      // Add user as a contributor
      await query(
        'general',
        `INSERT INTO pinboard_contributors (participant, pinboard) 
         VALUES ($1, $2) 
         ON CONFLICT DO NOTHING`,
        [user.uuid, pinboard]
      );

      // Fetch pinboard details
      const boardResult = await query(
        'general',
        'SELECT title FROM pinboards WHERE id = $1',
        [pinboard]
      );

      const board = boardResult.rows[0];

      if (!board) {
        throw new Error('Pinboard not found.');
      }

      // Send email notification
      await sendEmail(
        email,
        c_email || undefined,
        `[SDG Commons] - You have been added to the "${board.title}" board`,
        `
          <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <p>Dear ${user.name},</p>
            <br/>
            <p>We are excited to inform you that you have been added as a contributor to the board on <a href="https://www.sdg-innovation-commons.org/boards/all/${pinboard}" style="color: #007bff; text-decoration: none;"><strong>"${board.title}"</strong></a> on SDG Commons.</p>
            <p>As a contributor, you have been invited to keep track of content related to topic ${board.title}. As you browse content on the SDG Commons from now on, please remember to bookmark any content that you find interesting that is related to topic ${board.title}</p>
            <p>To view or contribute to this board, please log in to your account via the platform.</p>
            <p>If you have any questions or require assistance, feel free to reach out to ${username} or contact our support team.</p>
            <p>We look forward to your valuable contributions!</p>
            <br/>
            <p>Best regards,</p>
            <p>UNDP Accelerator Labs Team</p>
          </div>
        `
      );

      return {
        message: 'User found or created, and added as a contributor',
        success: true,
      };
    });

    return NextResponse.json(result);
  } catch (error) {
    console.error('Error handling user request:', error);
    const errorMessage =
      error instanceof Error ? error.message : 'An error occurred while processing the request.';
    return NextResponse.json(
      { message: errorMessage, success: false },
      { status: 400 }
    );
  }
}
