from sys import path as syspath
from os.path import join, dirname, exists
from shutil import copy

syspath.append(join(dirname(__file__)))
from compile_registry import generateFile, makeSafe

syspath.append(join(dirname(__file__), '..'))
from __registries__ import registries

def compileHome (registries):
  # print(registries)
  registries.sort(key=lambda x: x.get('title', ''))

  registries_dir = './registries'
  if not exists(registries_dir):
    makedirs(registries_dir)

  # Generate the main registry
  md = ''
  content = '<!-- !!DO NOT REMOVE THIS COMMENT!! start autogenerated hyperlinks -->\n'
  for r in registries:
    title = r.get('title', '')
    safe_title = makeSafe(title)
    md = md + f'- [{title}](./{safe_title})\n\n'

  content = content + md
  content = content + '<!-- !!DO NOT REMOVE THIS COMMENT!! end autogenerated hyperlinks -->'

  # Generate the README
  readme = join(registries_dir, 'README.md')
  generateFile(readme, 'The SDG Commons', content)
  # Generate the html file
  try:
    copy('./template.html', join(registries_dir, 'index.html'))
  except:
    print('an error occurred when trying to copy the template.html')

if __name__ == '__main__':
  compileHome(registries)