'use client';

import Link from 'next/link';
import { Button } from '@/app/ui/components/Button';
import { useRef } from 'react';
import { useIsVisible } from '@/app/ui/components/Interaction';

export default function Section() {

    const ref = useRef<HTMLDivElement>(null);
    const isVisible = useIsVisible(ref);

    return (
        <>
            <section className='lg:home-section lg:px-0 lg:py-0 !border-t-0'>
                <div className='section-content grid grid-cols-9 gap-[20px]'>
                    <div className="c-left lg:col-span-4 bg-[url('/images/about-us-2.jpeg')] bg-cover bg-no-repeat">
                        <div className='h-full w-full top-0 left-0 [background:linear-gradient(173.09deg,_rgba(1,_141,_242,_1),_rgba(237,_255,_164,_1))] opacity-[.5]' />
                        <div className='absolute top-0 left-0 lg:px-[80px] lg:py-[100px]'>
                            <h2 ref={ref} className={`yellow lg:mt-[5px] ${isVisible ? 'slanted-bg' : ''}`}>
                                <span>About the commons</span>
                            </h2>
                        </div>
                    </div>
                    <div className='c-right lg:col-span-5 lg:col-start-6 lg:pr-[80px] lg:py-[120px]'>
                        <p className='lead'>
                            <b>Welcome to UNDP Accelerator Lab Network's central hub for multi-country SDG learnings that features insights and ready-to-deploy solutions for the Sustainable Development Goals and many more behind-the-scenes activities of the Network.</b>
                        </p>
                        <div className='lg:columns-2 gap-[20px]'>
                            <p>Explore the early-stage results and insights generated by the Accelerator Labs Network in a suite of platforms newly released. These platforms are the first building blocks of an SDG Innovation Commons, a living hub of open knowledge where all UNDP colleagues – and, soon, academia, governments, civil society and private sector partners – are able to inquire and analyze the insights and data generated by the Labs and contribute to action-based learning on what it takes to reach the global Sustainable Development Goals.</p>
                            <p>We are constantly updating these platforms and curating the content available, reach out to us if you would like to be involved.</p>
                        </div>
                        <Button className="mt-[40px]">
                            <Link href={'#'}>
                                About Us
                            </Link>
                        </Button>
                    </div>
                </div>
            </section>
        </>
    );
}