import { Button } from '@/app/ui/components/Button';
import Link from 'next/link';

export default function Section() {

    return (

        <div className="relative w-full lg:flex-row flex flex-col items-start justify-start text-left text-9xl text-black">
            <div className="flex flex-row items-center justify-start w-full lg:h-full ">
                <div className="w-full h-[538.6px] flex flex-col items-start justify-start pt-10 pb-0 pl-5 pr-[33px] box-border relative gap-[6.2px] bg-[url('/images/about-us-2.jpeg')] bg-cover bg-no-repeat">
                    <div className="w-full !m-[0] absolute top-[0.34px] left-[0px] [background:linear-gradient(0deg,_rgba(3,_104,_177,_0.35),_rgba(237,_255,_164,_0.35))] h-[538px] z-[0]" />
                    <div className="flex flex-col items-start justify-start relative z-[1] px[20px] md:px-[40px]">
                        <div className="slanted-bg-yellow font-bold px-3">
                            <span>About the Commons</span>
                        </div>
                    </div>
                </div>
            </div>
            <div className="w-full flex flex-col items-start justify-start py-10 lg:py-0 px-5 box-border gap-[30px] lg:gap-0 text-2xl px[20px] md:px-[40px] lg:px-[131px] ">
                <b className="self-stretch relative leading-[28px]">Welcome to UNDP Accelerator Lab Network's central hub for multi-country SDG learnings that features insights and ready-to-deploy solutions for the Sustainable Development Goals and many more behind-the-scenes activities of the Network.</b>
                <div className="self-stretch relative text-base leading-[24px] lg:columns-2 gap-8 mt-5">
                    <p className="m-0 whitespace-pre-wrap">{`Explore the early-stage results and insights generated by the Accelerator Labs Network in a suite of platforms newly released. These platforms are the first building blocks of an SDG Innovation Commons, a living hub of open knowledge where all UNDP colleagues – and, soon, academia, governments, civil society and private sector partners – are able to inquire and analyze the insights and data generated by the Labs and contribute to action-based learning on what it takes to reach the global Sustainable Development Goals.`}</p>
                    <p className="m-0">We are constantly updating these platforms and curating the content available, reach out to us if you would like to be involved.</p>
                </div>

                <div className="self-stretch lg:self-auto  flex flex-col items-end justify-start text-center text-[14px] lg:pt-[30px] ">
                    <Button className="w-[166.3px] relative h-[53.8px]">
                        <Link href={'#'} className="leading-[22px] text-sm lg:text-lg ">
                            About Us
                        </Link>
                    </Button>
                </div>
            </div>
        </div>
    );
}